Mapper:
  item_id:
    MapperType: LatentFactor
    MapperParam:
      name: "item_id"
      LatentFactor_dim: 10
      id_num: 10000
  user_id:
    MapperType: LatentFactor
    MapperParam:
      name: "user_id"
      LatentFactor_dim: 10
      id_num: 10000
      

Interaction:
  interaction1:
    Input:
    - item_id
    - user_id
    InteractionType: MLP
    InteractionParam:
      param1: 10

Optimizer:
  OptimizerType: "RatingPrediction"
  OptimizerParam:
    LatentFactor_dim: 10
