Mapper:

  - LatentFactor:
      input:
        - user_id
      output: u
      params:
        embedding_dim: 10
        id_num: 10000

  - LatentFactor:
      input:
        - item_id
      output: v
      params:
        embedding_dim: 10
        id_num: 10000


Interactor:

  - MLP:
      input:
        - u
        - v
      output: interaction
      params:
        output_dim: 10


Optimizer:

  - RatingPrediction:
      input:
        - interaction
      output: rating
      params:
        latent_factor_dim: 10
