Mapper:

  - LatentFactor:
      input:
        - user_id
      output: u
      params:
        embedding_dim: 10
        id_num: 10000

  - LatentFactor:
      input:
        - item_id
      output: v
      params:
        embedding_dim: 10
        id_num: 10000


Interactor:

  - MLP:
      input:
        - u
        - v
      output: mlp_interaction
      params:
        layer_output_dim:
          - 128
          - 128
          - 128
          - 64

  - InnerProduct:
      input:
        - u
        - v
      output: inner_product_interaction


Optimizer:

  - RatingPrediction:
      input:
        - mlp_interaction
        - inner_product_interaction
      output: rating
      params:
        latent_factor_dim: 10
