Mapper:

  LatentFactor:
    params:
      embedding_dim: [[5, 10, 15], choice]
      id_num: 10000


Interactor:

  MLP:
    params:
      num_layers: [[1, 2, 3], choice]
      units: [[16, 32, 64, 128, 256, 512, 1024], choice]

  InnerProduct:

  VirtualBlock:
    block_choice: [MLP: , InnerProduct:]

Optimizer:

  RatingPrediction:
    params:
      latent_factor_dim: [[5, 10, 15], choice]
